--
-- PostgreSQL database dump
--


-- Dumped from database version 16.14 (Ubuntu 16.14-0ubuntu0.24.04.1)
-- Dumped by pg_dump version 16.14 (Ubuntu 16.14-0ubuntu0.24.04.1)


--
-- Name: customer; Type: SCHEMA; Schema: -; Owner: -
--

CREATE SCHEMA IF NOT EXISTS customer;




--
-- Name: customers; Type: TABLE; Schema: customer; Owner: -
--

CREATE TABLE customer.customers (
    customerid bigint NOT NULL,
    contactid bigint,
    orgnoid bigint NOT NULL,
    entitytypeid integer,
    created timestamp without time zone DEFAULT now(),
    updated timestamp without time zone,
    creator integer,
    updater integer
);


--
-- Name: TABLE customers; Type: COMMENT; Schema: customer; Owner: -
--

COMMENT ON TABLE customer.customers IS 'Customer';


--
-- Name: COLUMN customers.entitytypeid; Type: COMMENT; Schema: customer; Owner: -
--

COMMENT ON COLUMN customer.customers.entitytypeid IS 'Legal entitype';


--
-- Name: COLUMN customers.created; Type: COMMENT; Schema: customer; Owner: -
--

COMMENT ON COLUMN customer.customers.created IS 'Record creation timestamp';


--
-- Name: COLUMN customers.updated; Type: COMMENT; Schema: customer; Owner: -
--

COMMENT ON COLUMN customer.customers.updated IS 'Last update timestamp';


--
-- Name: COLUMN customers.creator; Type: COMMENT; Schema: customer; Owner: -
--

COMMENT ON COLUMN customer.customers.creator IS 'User who created the record';


--
-- Name: COLUMN customers.updater; Type: COMMENT; Schema: customer; Owner: -
--

COMMENT ON COLUMN customer.customers.updater IS 'User who last updated the record';


--
-- Name: customers_customerid_seq; Type: SEQUENCE; Schema: customer; Owner: -
--

ALTER TABLE customer.customers ALTER COLUMN customerid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME customer.customers_customerid_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: customers_orgnoid_seq; Type: SEQUENCE; Schema: customer; Owner: -
--

ALTER TABLE customer.customers ALTER COLUMN orgnoid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME customer.customers_orgnoid_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: entityroleusers; Type: TABLE; Schema: customer; Owner: -
--

CREATE TABLE customer.entityroleusers (
    roleuserid bigint NOT NULL,
    roleid integer NOT NULL,
    userid bigint NOT NULL,
    customerid bigint
);


--
-- Name: entityroleusers_roleuserid_seq; Type: SEQUENCE; Schema: customer; Owner: -
--

ALTER TABLE customer.entityroleusers ALTER COLUMN roleuserid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME customer.entityroleusers_roleuserid_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: entitytypenames; Type: TABLE; Schema: customer; Owner: -
--

CREATE TABLE customer.entitytypenames (
    entitytypenameid integer NOT NULL,
    entitypeid integer NOT NULL,
    languageid integer NOT NULL,
    entityname character varying(191) NOT NULL
);


--
-- Name: entitytypes; Type: TABLE; Schema: customer; Owner: -
--

CREATE TABLE customer.entitytypes (
    entitytypeid integer NOT NULL
);


--
-- Name: entitytypes_entitytypeid_seq; Type: SEQUENCE; Schema: customer; Owner: -
--

ALTER TABLE customer.entitytypes ALTER COLUMN entitytypeid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME customer.entitytypes_entitytypeid_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: invoiceitems; Type: TABLE; Schema: customer; Owner: -
--

CREATE TABLE customer.invoiceitems (
    invoiceitemid bigint NOT NULL,
    invoiceid bigint,
    description character varying(191) NOT NULL,
    number integer,
    price numeric(8,0),
    articleid bigint
);


--
-- Name: invoiceitems_invoiceitemid_seq; Type: SEQUENCE; Schema: customer; Owner: -
--

ALTER TABLE customer.invoiceitems ALTER COLUMN invoiceitemid ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME customer.invoiceitems_invoiceitemid_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: invoices; Type: TABLE; Schema: customer; Owner: -
--

CREATE TABLE customer.invoices (
    invoiceid bigint NOT NULL,
    customerid bigint,
    currencyid integer,
    invoicedate date DEFAULT now(),
    debt numeric(8,0) DEFAULT 0 NOT NULL
);


--
-- Name: invoices_invoiceid_seq; Type: SEQUENCE; Schema: customer; Owner: -
--

ALTER TABLE customer.invoices ALTER COLUMN invoiceid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME customer.invoices_invoiceid_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: orgnos; Type: TABLE; Schema: customer; Owner: -
--

CREATE TABLE customer.orgnos (
    orgnoid bigint NOT NULL,
    orgno character varying(191) NOT NULL,
    country integer NOT NULL,
    vatno character varying(25),
    moss boolean DEFAULT false
);


--
-- Name: COLUMN orgnos.vatno; Type: COMMENT; Schema: customer; Owner: -
--

COMMENT ON COLUMN customer.orgnos.vatno IS 'VAT registration number';


--
-- Name: COLUMN orgnos.moss; Type: COMMENT; Schema: customer; Owner: -
--

COMMENT ON COLUMN customer.orgnos.moss IS 'Mini One Stop Shop (EU VAT scheme)';


--
-- Name: orgnos_orgnoid_seq; Type: SEQUENCE; Schema: customer; Owner: -
--

ALTER TABLE customer.orgnos ALTER COLUMN orgnoid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME customer.orgnos_orgnoid_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: payments; Type: TABLE; Schema: customer; Owner: -
--

CREATE TABLE customer.payments (
    paymentid bigint NOT NULL,
    invoiceid integer NOT NULL,
    amount numeric(8,0) NOT NULL,
    paydate date DEFAULT now() NOT NULL
);


--
-- Name: payments_paymentid_seq; Type: SEQUENCE; Schema: customer; Owner: -
--

ALTER TABLE customer.payments ALTER COLUMN paymentid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME customer.payments_paymentid_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: services; Type: TABLE; Schema: customer; Owner: -
--

CREATE TABLE customer.services (
    serviceid bigint NOT NULL,
    customerid bigint NOT NULL,
    servicetypeid integer NOT NULL,
    websiteid bigint,
    datausage integer DEFAULT 0 NOT NULL
);


--
-- Name: services_serviceid_seq; Type: SEQUENCE; Schema: customer; Owner: -
--

ALTER TABLE customer.services ALTER COLUMN serviceid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME customer.services_serviceid_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: servicestypes; Type: TABLE; Schema: customer; Owner: -
--

CREATE TABLE customer.servicestypes (
    servicestypeid integer NOT NULL
);


--
-- Name: servicestypes_servicestypeid_seq; Type: SEQUENCE; Schema: customer; Owner: -
--

ALTER TABLE customer.servicestypes ALTER COLUMN servicestypeid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME customer.servicestypes_servicestypeid_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: servicetypenames; Type: TABLE; Schema: customer; Owner: -
--

CREATE TABLE customer.servicetypenames (
    servicetypenameid integer NOT NULL,
    languageid integer NOT NULL,
    servicetypeid integer NOT NULL,
    servicetypename character varying(191) NOT NULL
);


--
-- Name: servicetypenames_servicetypenameid_seq; Type: SEQUENCE; Schema: customer; Owner: -
--

ALTER TABLE customer.servicetypenames ALTER COLUMN servicetypenameid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME customer.servicetypenames_servicetypenameid_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: settings; Type: TABLE; Schema: customer; Owner: -
--

CREATE TABLE customer.settings (
    settingid bigint NOT NULL,
    customerid bigint NOT NULL,
    languageid integer DEFAULT 1 NOT NULL,
    currencyid integer NOT NULL,
    recommendedby text,
    period character varying(20) DEFAULT 'monthly'::character varying,
    invoicetype character varying(20) DEFAULT 'email'::character varying,
    vat numeric(5,4) DEFAULT 0.25,
    trust integer DEFAULT 0,
    active boolean DEFAULT true,
    newsletter boolean DEFAULT false,
    reference character varying(255),
    freetext text
);


--
-- Name: COLUMN settings.recommendedby; Type: COMMENT; Schema: customer; Owner: -
--

COMMENT ON COLUMN customer.settings.recommendedby IS 'Name of referring customer';


--
-- Name: COLUMN settings.period; Type: COMMENT; Schema: customer; Owner: -
--

COMMENT ON COLUMN customer.settings.period IS 'Billing period (monthly, quarterly, yearly)';


--
-- Name: COLUMN settings.invoicetype; Type: COMMENT; Schema: customer; Owner: -
--

COMMENT ON COLUMN customer.settings.invoicetype IS 'Invoice delivery method (email, paper, einvoice)';


--
-- Name: COLUMN settings.vat; Type: COMMENT; Schema: customer; Owner: -
--

COMMENT ON COLUMN customer.settings.vat IS 'VAT rate (0.25 = 25%)';


--
-- Name: COLUMN settings.trust; Type: COMMENT; Schema: customer; Owner: -
--

COMMENT ON COLUMN customer.settings.trust IS 'Trust level for payment terms';


--
-- Name: COLUMN settings.active; Type: COMMENT; Schema: customer; Owner: -
--

COMMENT ON COLUMN customer.settings.active IS 'Customer account is active';


--
-- Name: COLUMN settings.newsletter; Type: COMMENT; Schema: customer; Owner: -
--

COMMENT ON COLUMN customer.settings.newsletter IS 'Subscribed to newsletter';


--
-- Name: COLUMN settings.reference; Type: COMMENT; Schema: customer; Owner: -
--

COMMENT ON COLUMN customer.settings.reference IS 'Customer reference for invoices';


--
-- Name: COLUMN settings.freetext; Type: COMMENT; Schema: customer; Owner: -
--

COMMENT ON COLUMN customer.settings.freetext IS 'Free text notes about customer';


--
-- Name: settings_settingid_seq; Type: SEQUENCE; Schema: customer; Owner: -
--

ALTER TABLE customer.settings ALTER COLUMN settingid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME customer.settings_settingid_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: customers customers_pk; Type: CONSTRAINT; Schema: customer; Owner: -
--

ALTER TABLE ONLY customer.customers
    ADD CONSTRAINT customers_pk PRIMARY KEY (customerid);


--
-- Name: entityroleusers entityroleusers_pk; Type: CONSTRAINT; Schema: customer; Owner: -
--

ALTER TABLE ONLY customer.entityroleusers
    ADD CONSTRAINT entityroleusers_pk PRIMARY KEY (roleuserid);


--
-- Name: entitytypenames entitytypenames_pk; Type: CONSTRAINT; Schema: customer; Owner: -
--

ALTER TABLE ONLY customer.entitytypenames
    ADD CONSTRAINT entitytypenames_pk PRIMARY KEY (entitytypenameid);


--
-- Name: entitytypes entitytypes_pk; Type: CONSTRAINT; Schema: customer; Owner: -
--

ALTER TABLE ONLY customer.entitytypes
    ADD CONSTRAINT entitytypes_pk PRIMARY KEY (entitytypeid);


--
-- Name: invoiceitems invoiceitems_pk; Type: CONSTRAINT; Schema: customer; Owner: -
--

ALTER TABLE ONLY customer.invoiceitems
    ADD CONSTRAINT invoiceitems_pk PRIMARY KEY (invoiceitemid);


--
-- Name: invoices invoices_pk; Type: CONSTRAINT; Schema: customer; Owner: -
--

ALTER TABLE ONLY customer.invoices
    ADD CONSTRAINT invoices_pk PRIMARY KEY (invoiceid);


--
-- Name: orgnos orgnos_pk; Type: CONSTRAINT; Schema: customer; Owner: -
--

ALTER TABLE ONLY customer.orgnos
    ADD CONSTRAINT orgnos_pk PRIMARY KEY (orgnoid);


--
-- Name: orgnos orgnos_uq; Type: CONSTRAINT; Schema: customer; Owner: -
--

ALTER TABLE ONLY customer.orgnos
    ADD CONSTRAINT orgnos_uq UNIQUE (orgno, country) DEFERRABLE;


--
-- Name: payments payments_pk; Type: CONSTRAINT; Schema: customer; Owner: -
--

ALTER TABLE ONLY customer.payments
    ADD CONSTRAINT payments_pk PRIMARY KEY (paymentid);


--
-- Name: services services_pk; Type: CONSTRAINT; Schema: customer; Owner: -
--

ALTER TABLE ONLY customer.services
    ADD CONSTRAINT services_pk PRIMARY KEY (serviceid);


--
-- Name: servicestypes servicestypes_pk; Type: CONSTRAINT; Schema: customer; Owner: -
--

ALTER TABLE ONLY customer.servicestypes
    ADD CONSTRAINT servicestypes_pk PRIMARY KEY (servicestypeid);


--
-- Name: servicetypenames servicetypenames_pk; Type: CONSTRAINT; Schema: customer; Owner: -
--

ALTER TABLE ONLY customer.servicetypenames
    ADD CONSTRAINT servicetypenames_pk PRIMARY KEY (servicetypenameid);


--
-- Name: settings settings_pk; Type: CONSTRAINT; Schema: customer; Owner: -
--

ALTER TABLE ONLY customer.settings
    ADD CONSTRAINT settings_pk PRIMARY KEY (settingid);


--
-- Name: entityroleusers_roleid_idx; Type: INDEX; Schema: customer; Owner: -
--

CREATE INDEX entityroleusers_roleid_idx ON customer.entityroleusers USING btree (roleid, userid) INCLUDE (roleid, customerid);


--
-- Name: invoiceitems_invoiceid_idx; Type: INDEX; Schema: customer; Owner: -
--

CREATE INDEX invoiceitems_invoiceid_idx ON customer.invoiceitems USING btree (invoiceid) INCLUDE (invoiceid);


--
-- Name: payments_invoiceid_idx; Type: INDEX; Schema: customer; Owner: -
--

CREATE INDEX payments_invoiceid_idx ON customer.payments USING btree (invoiceid) INCLUDE (invoiceid);


--
-- Name: invoiceitems articles_fk; Type: FK CONSTRAINT; Schema: customer; Owner: -
--

ALTER TABLE ONLY customer.invoiceitems
    ADD CONSTRAINT articles_fk FOREIGN KEY (invoiceitemid) REFERENCES article.articles(articleid) ON DELETE SET NULL;


--
-- Name: customers contacts_fk; Type: FK CONSTRAINT; Schema: customer; Owner: -
--

ALTER TABLE ONLY customer.customers
    ADD CONSTRAINT contacts_fk FOREIGN KEY (contactid) REFERENCES account.contacts(contactid) ON UPDATE CASCADE ON DELETE SET NULL;


--
-- Name: orgnos countries_fk; Type: FK CONSTRAINT; Schema: customer; Owner: -
--

ALTER TABLE ONLY customer.orgnos
    ADD CONSTRAINT countries_fk FOREIGN KEY (country) REFERENCES public.countries(countryid) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: invoices currencies_fk; Type: FK CONSTRAINT; Schema: customer; Owner: -
--

ALTER TABLE ONLY customer.invoices
    ADD CONSTRAINT currencies_fk FOREIGN KEY (currencyid) REFERENCES public.currencies(currencyid);


--
-- Name: settings currencies_fk; Type: FK CONSTRAINT; Schema: customer; Owner: -
--

ALTER TABLE ONLY customer.settings
    ADD CONSTRAINT currencies_fk FOREIGN KEY (currencyid) REFERENCES public.currencies(currencyid) ON UPDATE CASCADE ON DELETE CASCADE DEFERRABLE;


--
-- Name: customers customers_creator_fk; Type: FK CONSTRAINT; Schema: customer; Owner: -
--

ALTER TABLE ONLY customer.customers
    ADD CONSTRAINT customers_creator_fk FOREIGN KEY (creator) REFERENCES account.users(userid) ON UPDATE CASCADE ON DELETE SET NULL;


--
-- Name: entityroleusers customers_fk; Type: FK CONSTRAINT; Schema: customer; Owner: -
--

ALTER TABLE ONLY customer.entityroleusers
    ADD CONSTRAINT customers_fk FOREIGN KEY (customerid) REFERENCES customer.customers(customerid) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: invoices customers_fk; Type: FK CONSTRAINT; Schema: customer; Owner: -
--

ALTER TABLE ONLY customer.invoices
    ADD CONSTRAINT customers_fk FOREIGN KEY (invoiceid) REFERENCES customer.customers(customerid) ON UPDATE CASCADE;


--
-- Name: services customers_fk; Type: FK CONSTRAINT; Schema: customer; Owner: -
--

ALTER TABLE ONLY customer.services
    ADD CONSTRAINT customers_fk FOREIGN KEY (customerid) REFERENCES customer.customers(customerid) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: settings customers_fk; Type: FK CONSTRAINT; Schema: customer; Owner: -
--

ALTER TABLE ONLY customer.settings
    ADD CONSTRAINT customers_fk FOREIGN KEY (customerid) REFERENCES customer.customers(customerid) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: customers customers_updater_fk; Type: FK CONSTRAINT; Schema: customer; Owner: -
--

ALTER TABLE ONLY customer.customers
    ADD CONSTRAINT customers_updater_fk FOREIGN KEY (updater) REFERENCES account.users(userid) ON UPDATE CASCADE ON DELETE SET NULL;


--
-- Name: customers entitytypes_fk; Type: FK CONSTRAINT; Schema: customer; Owner: -
--

ALTER TABLE ONLY customer.customers
    ADD CONSTRAINT entitytypes_fk FOREIGN KEY (entitytypeid) REFERENCES customer.entitytypes(entitytypeid) ON DELETE SET NULL;


--
-- Name: entitytypenames entitytypes_fk; Type: FK CONSTRAINT; Schema: customer; Owner: -
--

ALTER TABLE ONLY customer.entitytypenames
    ADD CONSTRAINT entitytypes_fk FOREIGN KEY (entitypeid) REFERENCES customer.entitytypes(entitytypeid) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: invoiceitems invoices_fk; Type: FK CONSTRAINT; Schema: customer; Owner: -
--

ALTER TABLE ONLY customer.invoiceitems
    ADD CONSTRAINT invoices_fk FOREIGN KEY (invoiceitemid) REFERENCES customer.invoices(invoiceid) ON DELETE CASCADE;


--
-- Name: payments invoices_fk; Type: FK CONSTRAINT; Schema: customer; Owner: -
--

ALTER TABLE ONLY customer.payments
    ADD CONSTRAINT invoices_fk FOREIGN KEY (invoiceid) REFERENCES customer.invoices(invoiceid) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: entitytypenames languages_fk; Type: FK CONSTRAINT; Schema: customer; Owner: -
--

ALTER TABLE ONLY customer.entitytypenames
    ADD CONSTRAINT languages_fk FOREIGN KEY (languageid) REFERENCES public.languages(languageid) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: servicetypenames languages_fk; Type: FK CONSTRAINT; Schema: customer; Owner: -
--

ALTER TABLE ONLY customer.servicetypenames
    ADD CONSTRAINT languages_fk FOREIGN KEY (languageid) REFERENCES public.languages(languageid) ON UPDATE CASCADE ON DELETE CASCADE DEFERRABLE;


--
-- Name: settings languages_fk; Type: FK CONSTRAINT; Schema: customer; Owner: -
--

ALTER TABLE ONLY customer.settings
    ADD CONSTRAINT languages_fk FOREIGN KEY (languageid) REFERENCES public.languages(languageid) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: customers orgnos_fk; Type: FK CONSTRAINT; Schema: customer; Owner: -
--

ALTER TABLE ONLY customer.customers
    ADD CONSTRAINT orgnos_fk FOREIGN KEY (orgnoid) REFERENCES customer.orgnos(orgnoid) ON DELETE SET NULL;


--
-- Name: entityroleusers roles_fk; Type: FK CONSTRAINT; Schema: customer; Owner: -
--

ALTER TABLE ONLY customer.entityroleusers
    ADD CONSTRAINT roles_fk FOREIGN KEY (roleid) REFERENCES account.roles(roleid) MATCH FULL ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: services services_websiteid_fk; Type: FK CONSTRAINT; Schema: customer; Owner: -
--



--
-- Name: services servicetypes_fk; Type: FK CONSTRAINT; Schema: customer; Owner: -
--

ALTER TABLE ONLY customer.services
    ADD CONSTRAINT servicetypes_fk FOREIGN KEY (servicetypeid) REFERENCES customer.servicestypes(servicestypeid) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: servicetypenames servicetypes_fk; Type: FK CONSTRAINT; Schema: customer; Owner: -
--

ALTER TABLE ONLY customer.servicetypenames
    ADD CONSTRAINT servicetypes_fk FOREIGN KEY (servicetypeid) REFERENCES customer.servicestypes(servicestypeid) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: entityroleusers users_fk; Type: FK CONSTRAINT; Schema: customer; Owner: -
--

ALTER TABLE ONLY customer.entityroleusers
    ADD CONSTRAINT users_fk FOREIGN KEY (userid) REFERENCES account.users(userid) MATCH FULL ON UPDATE CASCADE ON DELETE CASCADE;


--
-- PostgreSQL database dump complete
--
